[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
sa01_hello_world = "3GPCdFLptyRD2mXZoTFWbLwhk2ckTtfbMoJJnXnQv5Ct"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/wth000/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
